<?php

namespace Database\Seeders;

use App\Models\LegalDocument;
use Illuminate\Database\Seeder;

class LegalDocumentSeeder extends Seeder
{
    public function run(): void
    {
        LegalDocument::updateOrCreate(
            [
                'document_type' => LegalDocument::TYPE_TERMS,
                'version_number' => '1.0',
            ],
            [
                'content_text' => <<<TXT
LUMI Terms & Conditions

By creating an account and using LUMI, you agree to allow the application to collect eye-health telemetry (blink rate, viewing distance, screen time, and derived health scores) for dependent children under your guardianship for the purpose of parental monitoring and on-site clinical review via temporary access tokens.

You acknowledge that temporary clinician access is granted only through parent-generated codes that expire after fifteen (15) minutes, and that you may end any active viewing session at any time from the mobile application.

You agree not to misuse the platform, attempt to bypass role-based access controls, or share another user's credentials.
TXT,
                'published_at' => now(),
                'is_active' => true,
            ]
        );

        LegalDocument::updateOrCreate(
            [
                'document_type' => LegalDocument::TYPE_PRIVACY,
                'version_number' => '1.0',
            ],
            [
                'content_text' => <<<TXT
LUMI Privacy Policy

We collect account identity data, child profile data, device calibration settings, and eye-health metrics required to operate the service. Metrics are stored in our cloud database and may be cached offline on the guardian/child device.

Clinicians may view a child's telemetry only after redeeming a short-lived OTP/QR token generated by a guardian. Each viewing event is recorded in an immutable access log visible to guardians.

We do not sell personal data. Access logs and configuration change audits are retained to support transparency and academic project compliance.
TXT,
                'published_at' => now(),
                'is_active' => true,
            ]
        );
    }
}
